on:
 schedule:
   - cron:  "20,50 0-14,23 * * *"
 workflow_dispatch:
 watch:
    types: [started]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      run: |
        latest_version=`wget -O- https://pkgs.tailscale.com/stable/ | grep tailscale_ | head -1 | cut -d'_' -f 2`
        code=$(curl -sL -w %{http_code} --connect-timeout 20 --retry 5 'https://github.com/cyz0105/tailscale-openwrt/archive/refs/tags/${latest_version}.zip')
        result=$(echo $code | grep "200")
        
        if [[ "$result" != "" ]]; then
          echo -e "状态码200,存在不下载√√√√√"
        else
          echo -e "状态码$code,准备下载tgz包"
          curl -sL 'https://pkgs.tailscale.com/stable/tailscale_${latest_version}_amd64.tgz'
          ls
        fi
         
