on:
 schedule:
   - cron:  "20,50 0-14,23 * * *"
 workflow_dispatch:
 watch:
    types: [started]

jobs:
  sync_tailscale_latest_version:
    runs-on: ubuntu-latest
    steps:
    - name: check_latest_version
      run: |
        latest_version=$(wget -O- https://pkgs.tailscale.com/stable/ | grep tailscale_ | head -1 | cut -d'_' -f 2)
        echo "latest_version=$latest_version"  >> $GITHUB_ENV
        echo $latest_version
        
    - name: check_release_if_exist
      run: |
        code=`curl -I -m 10 -o /dev/null -s -w %{http_code} 'https://codeload.github.com/cyz0105/tailscale-openwrt/zip/refs/tags/${{ env.latest_version }}'`
        echo "http_code=$code"  >> $GITHUB_ENV
        echo $code
        
    - name: download
      if: ${{ env.http_code }} == "404"
      run: |
        echo "下载文件"
        curl --remote-name https://pkgs.tailscale.com/stable/tailscale_${{env.latest_version}}_amd64.tgz
        ls
        
        
    - name: Uploading...
      if: ${{ env.http_code }} == "404"
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./tailscale_${{env.latest_version}}_amd64.tgz
        asset_name: tailscale_${{env.latest_version}}_amd64.tgz
        asset_content_type: application/gzip
        
