on:
 schedule:
   - cron:  "20,50 0-14,23 * * *"
 workflow_dispatch:
 watch:
    types: [started]

jobs:
  sync_tailscale_latest_version:
    runs-on: ubuntu-latest
    steps:
    - name: check_latest_version
      run: |
        latest_version=$(wget -O- https://pkgs.tailscale.com/stable/ | grep tailscale_ | head -1 | cut -d'_' -f 2)
        echo "latest_version=$latest_version"  >> $GITHUB_ENV
        
    - name: check_release_if_exist
      run: |
        code=`curl -I -m 10 -o /dev/null -s -w %{http_code} 'https://codeload.github.com/cyz0105/tailscale-openwrt/zip/refs/tags/${{ env.latest_version }}.zip'`
        result=$(echo $code | grep "200")
        if [[ "$result" != "" ]]; then
          echo "is_exist=false" >> $GITHUB_ENV
        else
          echo "is_exist=true" >> $GITHUB_ENV
        fi
    - name: download
      if: ${{ env.is_exist }}
      run: |
        echo "下载文件代码块"
        
        
