on:
 schedule:
   - cron:  "20,50 0-14,23 * * *"
 watch:
    types: [started]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      run: |
        latest_version=`wget -O- https://pkgs.tailscale.com/stable/ | grep tailscale_ | head -1 | cut -d'_' -f 2`
        http_code=$(curl -sL -w %{http_code} --connect-timeout 20 --retry 5 -o https://github.com/${{ github.repository }}/archive/refs/tags/${latest_version}.zip)
        # result=$(echo $http_code | grep "200")
        echo $(echo $http_code | grep "200")

        # if [[ "$(test_connect $1)" -eq "200" ]]; then
        
        wget https://github.com/${{ github.repository }}/archive/refs/tags/${latest_version}.zip 
        echo ${latest_version}
        
        
        ls
