name: Run tar.sh on Push and Star

on:
  push:
    branches:
      - main  # 适当地更改分支名称
  watch:
    types:
      - started

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Run tar.sh and Upload
      run: |
        tar -czvf tailscale-openwrt.tgz usr/ etc/ || tar c -zvf tailscale-openwrt.tgz usr/ etc/
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Upload the latest tar.gz file"
        git push origin HEAD:main
